env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react', 'sort-class-members']

settings:
  react:
    version: '16'

rules: {
  sort-class-members/sort-class-members: [2, {
    order: [
      '[static-properties]',
      '[static-methods]',
      '[properties]',
      '[conventional-private-properties]',
      constructor,
      '[methods]',
      '[conventional-private-methods]'
    ],
    accessorPairPositioning: getThenSet,
  }]
}
